name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Debug Installed Packages
        run: pip freeze  # This will print installed packages in the logs

      - name: Debug File Encoding and Line Endings
        run: |
          file main.py
          cat -A main.py

      - name: Ensure Unix Line Endings
        run: |
          git config --global core.autocrlf input
          git checkout -- .

      - name: Debug Python Execution
        run: python -v main.py

      - name: Run Tests
        run: pytest

      - name: Debug Installed Packages
        run: pip freeze  # This will print installed packages in the logs

      - name: Run Tests
        run: pytest
# Force trigger CI
