name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to AWS EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd fastapi-book-project
            git pull origin main
            docker build -t fastapi-app .

            echo "Checking for running containers..."
            docker ps  # Debugging step to see running containers

            echo "Stopping and removing existing container if it exists..."
            docker stop fastapi-app || true
            docker rm -f fastapi-app || true  # Force remove if needed

            echo "Ensuring no process is using port 8000..."
            sudo fuser -k 8000/tcp || true  # Kill any process using port 8000

            echo "Removing old Docker images (if any)..."
            docker system prune -f

            echo "Starting new container..."
            docker run -d -p 8000:8000 --name fastapi-app fastapi-app

            echo "Restarting Nginx..."
            sudo systemctl restart nginx
